### ISSUE TITLE
General failure with accessing structure member named same as proc

### ISSUE THREAD

**Issue by vid512** [Terraspace/UASM#145] opened 2021-04-10 17:29 UTC
Following code crashes UASM 2.51. The instruction tries to get type of structure member, a member which has same name as prototype of PROC. 

```
.code

myproc proto

mov [(type something.myproc) ptr [rax]], rax

a db 0

myproc PROC
  RET
myproc ENDP

end
```

I had many other variants of same problem, this is just the minimal version I could reproduce. I assume it's some kind of wrong handling in 'type' operator of structure member named same as PROC prototype.

**Comment by vid512** [comment] 2021-04-10 21:28
I have just realized this is most likely only a simpler variant of previously reported problem: https://github.com/Terraspace/UASM/issues/132

**Comment by john-terraspace** [comment] 2022-03-21 17:49
Couldn't reproduce this issue using this test-case:

.x64
.model flat

something STRUCT
	myproc dq ?
something ENDS

.code

myproc proto

mov [(type something.myproc) ptr [rax]], rax

a db 0

myproc PROC
  RET
myproc ENDP

end

**Comment by john-terraspace** [comment] 2022-03-21 17:54
Moving this to #132 and closing.

**Closed by john-terraspace** 2022-03-21 17:54 UTC
